### ISSUE TITLE
BMI Calculator 

### ISSUE THREAD

**Issue by RunTimeError02** [Git-For-Geeks/Python-projects#44]
BMI is a measure of relative weight based on an individual’s mass and height. Today, Body Mass Index is commonly used to classify people as underweight, overweight, and even with obesity. Also, it is adopted by countries to promote healthy eating.
BMI Calculator with python:
The body mass index is calculated by dividing an individual’s weight in kilograms by their height in meters, then dividing the answer again by their height.

**Comment by Stutiagrawal10** [comment]
@RunTimeError02 please try to take a project from the existing one's. I cannot assign you this project because BMI calculation is just a formula so cannot be considered as a project.
